### ISSUE TITLE
Coundn't build plugin on lazyvim : Failed to spawn process luarocks.bat

### ISSUE THREAD

**Issue by Zim-Inn** [mrcjkb/neotest-haskell#196] opened 2024-10-04 18:15 UTC
### Question

I am new to neovim editor.
I run neovim on windows powershell via windows terminal.
I add haskell language surpport by edit lazyvim extra config on its tui.
And then it clone neotest-haskell after restart neovim successfully.
![image](https://github.com/user-attachments/assets/be403e08-74f6-4bdc-a792-04f3d901bf35)

But finally a failure occurred and the plugin didn't enable.

![image](https://github.com/user-attachments/assets/4b5fc978-094a-40e2-abef-449ba87802e3)

It says
![image](https://github.com/user-attachments/assets/2e00d476-068d-417b-ba8a-d82ceebd287b)

I search my local files include hidden files. It can't be found which named luarocks.bat

The only result is 
![image](https://github.com/user-attachments/assets/13664114-5baa-4b60-b2f5-6644ab544ed9)

How can I resolve it?

My local c complier is zig. And I have already install haskell toolchain by ghcup.

**Comment by mrcjkb** [comment] 2024-10-04 19:23
Duplicate of #179

**Closed by mrcjkb** 2024-10-04 19:23 UTC
Labels: question
